import { expect, test } from '@playwright/test'

test('admin demo saves a cinema and keeps payment details read-only', async ({ page }) => {
  await page.goto('/admin/cinemas')
  await expect(page.getByRole('heading', { name: 'Rạp chiếu phim', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Thêm rạp' }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('Tên rạp').fill('Cinémat Test Central')
  await dialog.getByLabel('Thành phố').fill('Đà Nẵng')
  await dialog.getByLabel('Địa chỉ').fill('100 Đường Demo')
  await dialog.getByRole('button', { name: 'Lưu thay đổi' }).click()
  await expect(dialog).not.toBeVisible()
  await page.reload()
  await page.getByRole('searchbox', { name: 'Tìm kiếm danh sách' }).fill('Test Central')
  await expect(page.getByRole('heading', { name: 'Cinémat Test Central' })).toBeVisible()
  await expect(page.getByText('Phòng 01', { exact: true })).toBeVisible()
  await page.goto('/admin/payments?status=FAILED')
  await expect(page.getByRole('combobox', { name: 'Lọc danh sách' })).toHaveValue('FAILED')
  await page.getByRole('button', { name: /Chi tiết giao dịch/ }).first().click()
  await expect(page.getByRole('dialog').getByText('Thất bại', { exact: true })).toBeVisible()
  await expect(page.getByRole('dialog').getByRole('button', { name: /hoàn tiền|xác nhận thanh toán/i })).toHaveCount(0)
  await page.getByRole('button', { name: 'Đóng chi tiết' }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: 'Mở menu quản trị' }).click()
  await page.getByRole('navigation', { name: 'Điều hướng quản trị' }).getByRole('link', { name: 'Phim', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Quản lý phim', exact: true })).toBeVisible()
})
